Repository Automattic/wc-calypso-bridge, pull requests merged in 2018-11, with the labels that each got.

#126 Forms design updates
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#128 Setup checklist: Add missing conditionals and sidebar count
  assets/css/setup-checklist.css
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#121 reccomend spelling and comma
  store-on-wpcom/inc/class-customizer-guided-tour.php
Labels: [Status] Ready to Merge

#127 Update large buttons
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#130 Setup checklist: Header/footer, hide completed, "I'm done"
  assets/css/calypsoify.css
  assets/css/setup-checklist.css
  assets/images/woocommerce-setup.svg
  assets/js/setup-checklist.js
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#131 Fix subscription connection menu link colors
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#132 Fix long site title display on Calypsoify pages
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#133 Track events inside OBW and checklist
  assets/js/calypsoify-obw.js
  assets/js/calypsoify.js
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
  includes/class-wc-calypso-bridge-admin-setup-wizard.php
Labels: [Status] Needs Review, eCommerce Plan

#129 Add calypso notice styling
  assets/css/calypsoify.css
  assets/js/calypsoify.js
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#138 Fix masterbar to top of screen and fix gap
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#139 Remove padding from title wrap
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#140 Add mobile styling to checklist page
  assets/css/calypsoify.css
  assets/css/setup-checklist.css
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#142 Add an early param check for calypsoify
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#150 Hide Woo OBW admin alert.
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-hide-alerts.php
Labels: [Status] Needs Review, eCommerce Plan

#156 Align page title actions to the right
  assets/css/calypsoify.css
  assets/js/calypsoify.js
Labels: [Status] Ready to Merge, eCommerce Plan

#157 Hide manual payments in OBW.
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#158 Add Calypsoify pagination
  assets/css/calypsoify.css
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-pagination.php
Labels: [Status] Ready to Merge, eCommerce Plan

#159 Move notices beneath subnavigation
  assets/css/calypsoify.css
  assets/js/calypsoify.js
Labels: [Status] Ready to Merge, eCommerce Plan

#163 Hide payment settings config in OBW
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#160 Remove add new product menu item
  includes/class-wc-calypso-bridge-page-controller.php
Labels: [Status] Needs Review, eCommerce Plan

#166 Add gridicons as composer package
  README.md
  assets/css/setup-checklist.css
  assets/js/calypsoify.js
  class-wc-calypso-bridge.php
  composer.json
  composer.lock
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
  includes/class-wc-calypso-bridge-menus.php
Labels: [Status] Needs Review, eCommerce Plan

#162 Add taxonomy form toggle
  assets/css/calypsoify.css
  assets/js/calypsoify.js
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-taxonomies.php
Labels: eCommerce Plan

#164 Calypso style search and subnav search
  assets/css/calypsoify.css
  assets/js/calypsoify.js
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#176 Update logic for determining if a site is an eCommerce site
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#161 Add calypso styling to form inputs
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#168 Remove folded menu on tablet viewport
  assets/css/calypsoify.css
  assets/js/calypsoify.js
Labels: [Status] Ready to Merge, eCommerce Plan

#174 Add action header actions
  assets/css/calypsoify.css
  assets/js/calypsoify.js
  includes/class-wc-calypso-bridge-action-header.php
Labels: [Status] Ready to Merge, eCommerce Plan

#175 Remove page titles and move page actions to action header
  assets/css/calypsoify.css
  assets/js/calypsoify.js
  includes/class-wc-calypso-bridge-action-header.php
Labels: [Status] Ready to Merge, eCommerce Plan

#180 Fix publishing button and action alignment
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#181 Remove create new submenu items for all post types
  includes/class-wc-calypso-bridge-menus.php
  includes/class-wc-calypso-bridge-page-controller.php
Labels: [Status] Ready to Merge, eCommerce Plan

#177 Fix system status copy notice display
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#183 Update loading order so our updates only apply on WC pages
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-action-header.php
  includes/class-wc-calypso-bridge-menus.php
Labels: [Status] Ready to Merge, eCommerce Plan

#185 Update version to 1.0.1
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#184 Add "Powered by WooCommerce" footer
  assets/css/calypsoify.css
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#186 Manually bundle gridicons
  class-wc-calypso-bridge.php
  composer.json
  includes/gridicons.php
Labels: [Status] Ready to Merge, eCommerce Plan

#194 Fix Calypsoify on Woo Post Types
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge

#199 Get breadcrumbs parent URL from first submenu item
  includes/class-wc-calypso-bridge-action-header.php
Labels: [Status] Ready to Merge, eCommerce Plan

#200 Prevent FOUC for admin notices
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#201 Fix input alignment issues with checkboxes and select2
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#202 Move notices on any page with subnav
  assets/js/calypsoify.js
Labels: [Status] Ready to Merge, eCommerce Plan

#188 Hides all plugin activation and wp-admin admin notices in the calypso…
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-helper-functions.php
  includes/class-wc-calypso-bridge-hide-alerts.php
Labels: [Status] Needs Review, eCommerce Plan

#189 Adds Theme defaults
  class-wc-calypso-bridge-frontend.php
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
  includes/class-wc-calypso-bridge-themes-setup.php
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#203 Add Jetpack dependencies early on to prevent breaking disconnected sites
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#204 Fix setup list margins for new layout padding
  assets/css/calypsoify.css
  assets/css/setup-checklist.css
Labels: [Status] Needs Review, eCommerce Plan

#206 Bump version to 1.0.2
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, eCommerce Plan

#210 Hide all actions on mobile except first in action header
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#211 Hide hidden notices
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#216 Update selectors for wc status notices
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#217 Fix table action button height
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#229 Modifies the default text for the store notice.
  includes/class-wc-calypso-bridge-themes-setup.php
Labels: [Status] Ready to Merge, eCommerce Plan

#226 Hide large Klarna setup banners
  includes/class-wc-calypso-bridge-hide-alerts.php
Labels: [Status] Ready to Merge, eCommerce Plan

#227 Fix selected sidebar menu styles
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#219 Expand submenu in sidebar on tablets
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#220 Append notices to first subnav only
  assets/js/calypsoify.js
Labels: [Status] Needs Review, eCommerce Plan

#225 Fix JITM notice styles to match Calypso
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#228 Fix modal styles
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#235 Update wc tracking checkbox color
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#238 Fix notice height and padding
  assets/css/calypsoify.css
Labels: [Status] Needs Review, bug, eCommerce Plan

#239 Always load Calypsoify during the setup wizard.
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-setup.php
Labels: [Status] Ready to Merge, eCommerce Plan

#240 Bump version to 1.0.3
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, eCommerce Plan

#251 Fixes situations where Calypsoified pages will still output the admin…
  class-wc-calypso-bridge.php
Labels: bug, eCommerce Plan

#257 Fix stylesheet orders in OBW to restore masterbar
  includes/class-wc-calypso-bridge-setup.php
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#255 Use click based tracking for Stripe task in setup
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#221 Add dropdown toggle for subnavs on mobile
  assets/css/calypsoify.css
  assets/js/calypsoify.js
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#259 Automatically activate shipping based on geolocation
  includes/class-wc-calypso-bridge-admin-setup-wizard.php
Labels: [Status] Needs Review, eCommerce Plan

#262 Hide WC core notices
  includes/class-wc-calypso-bridge-hide-alerts.php
Labels: [Status] Needs Review, eCommerce Plan

#263 Fig taxonomy form inconsistencies and tag successful message
  assets/css/calypsoify.css
  assets/js/calypsoify.js
  class-wc-calypso-bridge.php
Labels: [Status] Needs Review, eCommerce Plan

#264 Updates select boxes and buttons in table filters to match calypso styles
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#261 Wait for link track completion and continue to href
  assets/js/calypsoify.js
Labels: [Status] Needs Review, bug, eCommerce Plan

#277 Fix select and select button line height
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#266 Align nav tabs left on smaller screens
  assets/css/calypsoify.css
Labels: eCommerce Plan

#269 Store added tags on load to prevent 'add' notice on dom tree changes
  assets/js/calypsoify.js
Labels: [Status] Needs Review, bug, eCommerce Plan

#270 Move h2 action buttons to action header
  assets/css/calypsoify.css
  assets/js/calypsoify.js
Labels: eCommerce Plan

#272 Use 'Add new' toggle form pattern for product attributes
  assets/css/calypsoify.css
  assets/js/calypsoify.js
  includes/class-wc-calypso-bridge-taxonomies.php
Labels: eCommerce Plan

#275 Fix WC Bookings table on mobile
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#271 Add card styling to product addons form
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#273 Simplify products table on mobile
  assets/css/calypsoify.css
Labels: eCommerce Plan

#283 Add select2 token styling
  assets/css/calypsoify.css
Labels: eCommerce Plan

#284 Add dropdown for nav tabs
  assets/css/calypsoify.css
  assets/js/calypsoify.js
Labels: [Status] Needs Review, eCommerce Plan

#289 Redirect to setup checklist if no payment gateways are available
  includes/class-wc-calypso-bridge-admin-setup-wizard.php
Labels: eCommerce Plan

#290 Add table cell padding and fix alignment
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#318 Add WooCommerce as a dependency
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#316 Use search label as placeholder for search inputs
  assets/js/calypsoify.js
Labels: [Status] Ready to Merge, eCommerce Plan

#315 Remove space on top of checklist page image
  assets/css/setup-checklist.css
Labels: [Status] Ready to Merge, eCommerce Plan

#314 Update hard-coded icons to use get_gridicons
  assets/js/calypsoify.js
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-action-header.php
Labels: [Status] Ready to Merge, eCommerce Plan

#313 Change WC menu item to 'Store'
  assets/css/calypsoify.css
  assets/images/cart-dark.png
  assets/images/cart-white.png
  includes/class-wc-calypso-bridge-menus.php
Labels: [Status] Ready to Merge, eCommerce Plan

#311 Fix WC settings select dropdown
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#310 Fix error content height
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#309 Fix styling and alignment for nav-tabs outside of wrapper
  assets/css/calypsoify.css
  assets/js/calypsoify.js
Labels: [Status] Ready to Merge, eCommerce Plan

#308 Change submit actions to large buttons
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#307 Add history state for taxonomy form toggle
  assets/js/calypsoify.js
Labels: [Status] Ready to Merge, eCommerce Plan

#285 Add styling for select2 clear icon
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#265 Prep for 1.0.4 release
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge

#330 Prevent WooCommerce deactivation
  includes/class-wc-calypso-bridge-plugins.php
Labels: [Status] Ready to Merge, eCommerce Plan

#331 Fix button hover states
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#332 Remove Akismet dismiss button
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#333 Move setup menu item to top level
  includes/class-wc-calypso-bridge-action-header.php
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
  includes/connect/wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#335 Make new post pages full width
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#339 Fix a JS error preventing "my sites" from working during the OBW
  assets/js/calypsoify-obw.js
Labels: [Status] Ready to Merge, eCommerce Plan

#341 Flush rewrite rules during setup.
  includes/class-wc-calypso-bridge-admin-setup-wizard.php
Labels: [Status] Ready to Merge, eCommerce Plan

#349 Remove clear icon from select2
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#350 Update OBW to match Calypso's style
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#353 Restore OBW payment settings
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#354 Fix table manager table
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#355 Restore table action styling
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#358 Focus select2 search field when opened
  assets/js/calypsoify.js
Labels: [Status] Ready to Merge, eCommerce Plan

#359 Hides admin notices for Storefront Powerpack Extensions:
  includes/class-wc-calypso-bridge-hide-alerts.php
Labels: [Status] Ready to Merge, eCommerce Plan

#340 Only show Apple Pay notice on settings page
  includes/class-wc-calypso-bridge-hide-alerts.php
Labels: [Status] Ready to Merge, eCommerce Plan

#366 Reduce Facebook and Mailchimp task times
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#367 Fix extra stripe notices display
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#365 Make PayPal and Stripe steps both click and setting based.
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#351 Fix setup checklist redirect when logged out
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#348 Remove product attribute descriptions
  includes/class-wc-calypso-bridge-taxonomies.php
Labels: [Status] Ready to Merge, eCommerce Plan

#369 Change wc helper table background colors to prevent overlapping
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#371 Update WC helper button selector specificity
  assets/css/calypsoify.css
Labels: [Status] Needs Review, eCommerce Plan

#370 Change card style headings to direct children only
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#376 Make checklist action button large again
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#373 Remove setup count caching
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#374 Add mailchimp form styles
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#372 Add pagination to taxonomies
  assets/css/calypsoify.css
  includes/class-wc-calypso-bridge-pagination.php
Labels: [Status] Ready to Merge, eCommerce Plan

#363 Bump version to 1.0.5
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#377 Fix checkmark color
  assets/css/setup-checklist.css
Labels: [Status] Ready to Merge, eCommerce Plan

#401 Hide installed extensions from search results on the "Extensions" screen
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-addons-screen.php
  includes/class-wc-calypso-bridge-addons.php
Labels: [Status] Ready to Merge, eCommerce Plan

#400 Remove clear icon in inputs in ie11
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#398 Fix setup header image in ie11
  assets/css/setup-checklist.css
Labels: [Status] Ready to Merge, eCommerce Plan

#397 Remove order actions button margin
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#334 Add setup checklist return notice
  assets/css/calypsoify.css
  assets/js/calypsoify.js
  assets/js/setup-checklist.js
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#379 Move Stripe above PayPal in setup checklist
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#393 Vertically center site icon
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#394 Fix action header button sizes
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#395 Fix Orders table layout
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#396 Fix the gridicons size
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#399 Remove select arrow dropdowns in IE11
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#403 Fix JITM notice styling
  assets/css/calypsoify.css
  assets/js/calypsoify.js
Labels: [Status] Ready to Merge, eCommerce Plan

#404 Fix date/time and address formatting on orders pages
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#405 Navigation to calypso update
  assets/css/calypsoify.css
  includes/class-wc-calypso-bridge-action-header.php
  includes/class-wc-calypso-bridge-menus.php
  includes/connect/wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#406 Fixes the problem where Powerpack Designer, Mega Menus, and Pricing T…
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#407 Bump version to 1.0.6
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan
