Repository Automattic/wc-calypso-bridge, pull requests merged in 2018-10, with the labels that each got.

#58 Add page registration system and basic menu handling
  includes/connect/core.php
  includes/connect/mailchimp-for-woocommerce.php
  includes/menus.php
  includes/page-controller.php
  wc-calypso-bridge-class.php
Labels: [Status] Needs Review

#57 Remove add_settings_error
  inc/wc-calypso-bridge-mailchimp-add-settings-error.php
  wc-calypso-bridge-class.php
Labels: [Status] Needs Review

#59 Add WC Calypsoify support for bundled extensions
  includes/connect/core.php
  includes/connect/mailchimp-for-woocommerce.php
  includes/connect/woocommerce-product-addons.php
  includes/connect/woocommerce-services.php
  includes/page-controller.php
Labels: [Status] Ready to Merge

#66 Register support for extensions (batch 1)
  includes/connect/core.php
  includes/connect/woocommerce-bookings.php
  includes/connect/woocommerce-checkout-field-editor.php
  includes/connect/woocommerce-conditional-shipping-and-payments.php
  includes/connect/woocommerce-customer-order-csv-export.php
  includes/connect/woocommerce-deposits.php
  includes/connect/woocommerce-dynamic-pricing.php
  includes/connect/woocommerce-follow-up-emails.php
  includes/connect/woocommerce-memberships.php
  includes/connect/woocommerce-pip.php
  includes/connect/woocommerce-product-feeds.php
  includes/connect/woocommerce-services.php
  includes/connect/woocommerce-smart-coupons.php
  includes/connect/woocommerce-subscriptions.php
  includes/connect/woocommerce-zapier.php
Labels: [Status] Ready to Merge

#72 Add setup class and remove unused steps
  includes/setup.php
  store-on-wpcom/inc/wc-calypso-bridge-mailchimp-add-settings-error.php
  wc-calypso-bridge-class.php
Labels: [Status] Ready to Merge, eCommerce Plan

#74 Add final batch of extensions
  includes/connect/woocommerce-box-office.php
  includes/connect/woocommerce-lightspeed-pos.php
  includes/connect/woocommerce-pdf-invoice.php
  includes/connect/woocommerce-pdf-product-vouchers.php
  includes/connect/woocommerce-shipping-stamps.php
  includes/connect/woocommerce-tab-manager.php
  includes/connect/woocommerce-wishlists.php
Labels: [Status] Needs Review, eCommerce Plan

#73 Add masterbar to setup wizard
  includes/setup-wizard.php
  includes/setup.php
Labels: [Status] Ready to Merge, eCommerce Plan

#84 Update remove WC logo
  includes/setup-wizard.php
Labels: [Status] Ready to Merge, eCommerce Plan

#86 Fix some design issues with WooCommerce extensions
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#82 Fix design issues with core
  assets/css/calypsoify.css
  wc-calypso-bridge-class.php
Labels: [Status] Needs Review, eCommerce Plan

#91 Update OBW step headings
  assets/css/calypsoify.css
  includes/setup-wizard.php
  includes/setup.php
Labels: [Status] Ready to Merge, eCommerce Plan

#94 Change wc colors to calypsoify colors
  assets/css/calypsoify.css
  assets/js/calypsoify-obw.js
  includes/setup-wizard.php
Labels: [Status] Ready to Merge, eCommerce Plan

#90 Add phpcs and format files
  .gitignore
  composer.json
  composer.lock
  includes/class-wc-calypso-bridge-admin-setup-wizard.php
  includes/class-wc-calypso-bridge-menus.php
  includes/class-wc-calypso-bridge-page-controller.php
  includes/class-wc-calypso-bridge-setup.php
  includes/connect/core.php
  includes/connect/mailchimp-for-woocommerce.php
  includes/connect/woocommerce-avatax.php
  includes/connect/woocommerce-bookings.php
  includes/connect/woocommerce-box-office.php
  includes/connect/woocommerce-catalog-visibility-options.php
  includes/connect/woocommerce-checkout-add-ons.php
  includes/connect/woocommerce-checkout-field-editor.php
  includes/connect/woocommerce-conditional-shipping-and-payments.php
  includes/connect/woocommerce-cost-of-goods.php
  includes/connect/woocommerce-customer-order-csv-export.php
  includes/connect/woocommerce-customer-order-csv-import.php
  includes/connect/woocommerce-deposits.php
  includes/connect/woocommerce-dynamic-pricing.php
  includes/connect/woocommerce-follow-up-emails.php
  includes/connect/woocommerce-lightspeed-pos.php
  includes/connect/woocommerce-memberships.php
  includes/connect/woocommerce-name-your-price.php
  includes/connect/woocommerce-order-status-manager.php
  includes/connect/woocommerce-pdf-invoice.php
  includes/connect/woocommerce-pdf-product-vouchers.php
  includes/connect/woocommerce-pip.php
  includes/connect/woocommerce-points-and-rewards.php
  includes/connect/woocommerce-pre-orders.php
  includes/connect/woocommerce-product-addons.php
  includes/connect/woocommerce-product-csv-import-suite.php
  includes/connect/woocommerce-product-feeds.php
  includes/connect/woocommerce-product-search.php
  includes/connect/woocommerce-product-vendors.php
  includes/connect/woocommerce-services.php
  includes/connect/woocommerce-shipping-local-pickup-plus.php
  includes/connect/woocommerce-shipping-stamps.php
  includes/connect/woocommerce-smart-coupons.php
  includes/connect/woocommerce-social-login.php
  includes/connect/woocommerce-subscriptions.php
  includes/connect/woocommerce-tab-manager.php
  includes/connect/woocommerce-wishlists.php
  includes/connect/woocommerce-xero.php
  includes/connect/woocommerce-zapier.php
  includes/setup.php
  phpcs.xml.dist
  wc-calypso-bridge-class.php
  wc-calypso-bridge.php
Labels: [Status] Needs Review, eCommerce Plan

#95 Fix Calypsoify compatibility with WooCommerce and Gutenberg
  includes/class-wc-calypso-bridge-menus.php
  includes/gutenberg.php
  wc-calypso-bridge-class.php
Labels: [Status] Ready to Merge, eCommerce Plan

#98 Update store setup form styling
  assets/css/calypsoify.css
  assets/js/calypsoify-obw.js
  includes/class-wc-calypso-bridge-admin-setup-wizard.php
Labels: [Status] Ready to Merge, eCommerce Plan

#97 Adds setup checklist base
  assets/css/calypsoify.css
  includes/class-wc-calypso-bridge-setup-checklist.php
  includes/connect/wc-calypso-bridge.php
  wc-calypso-bridge-class.php
Labels: [Status] Needs Review, eCommerce Plan

#107 Add dark Klarna and Square logos for payment gateways
  assets/css/calypsoify.css
  assets/images/klarna.png
  assets/images/square.png
Labels: [Status] Ready to Merge, eCommerce Plan

#115 Update calypso button styles
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#117 Add payment gateway settings and email settings breadcrumbs
  assets/css/calypsoify.css
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-breadcrumbs.php
Labels: [Status] Ready to Merge, eCommerce Plan

#114 Generic table design updates
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#123 Add nav tab active state colors
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#125 Fix masterbar hover state and product add-ons compatibility
  assets/css/calypsoify.css
  includes/connect/woocommerce-product-addons.php
Labels: [Status] Ready to Merge, eCommerce Plan

#116 Add setup tasks and base list rendering code
  assets/css/setup-checklist.css
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan
