Repository Automattic/wc-calypso-bridge, pull requests merged in 2018-12, with the labels that each got.

#413 Handles setup for Storefront Starter Content by redirecting to the cu…
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
  includes/class-wc-calypso-bridge-helper-functions.php
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#411 Fix orders table layout on mobile
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#410 Fix checklist action button colors
  assets/css/setup-checklist.css
Labels: [Status] Ready to Merge, eCommerce Plan

#408 Fix IE11 input heights
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan

#412 Add Calypsoify testing instructions to README
  README.md
Labels: eCommerce Plan

#418 Redirect the checklist to the setup wizard if setup hasn't occurred yet
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#419 Add support links with tracking
  assets/css/calypsoify.css
  assets/js/calypsoify.js
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-menus.php
  includes/connect/wc-calypso-bridge.php
Labels: [Status] Needs Review, eCommerce Plan

#420 Bump version to 1.0.8
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: eCommerce Plan

#423 Store on WP.com: Fix fatal error on MailChimp deactivation + 1.0.9 bump
  composer.json
  readme.txt
  store-on-wpcom/inc/wc-calypso-bridge-mailchimp-deactivate-hook.php
  wc-calypso-bridge.php
Labels: Store on WP.com, [Status] Ready to Merge
