Repository Automattic/wc-calypso-bridge, pull requests merged in 2019-07, with the labels that each got.

#471 add WooCommerce Admin top level pages to bridge
  includes/connect/woocommerce-admin.php
Labels: [Status] Ready to Merge, eCommerce Plan

#474 use array_shift to get first array element
  includes/class-wc-calypso-bridge-action-header.php
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#476 Check Jetpack dependencies before modifying the WooCommerce setup wizard.
  includes/class-wc-calypso-bridge-setup.php
Labels: [Status] Ready to Merge, eCommerce Plan

#475 Check for product count instead of click in checklist
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#473 update readme with current dev environment set up instructions
  README.md
Labels: [Status] Ready to Merge, eCommerce Plan, task

#482 remove temporary CSS
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, eCommerce Plan, task

#480 Add default payment gateway task
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Ready to Merge, eCommerce Plan

#481 use jQuery to copy WC Admin breadcrumbs to Calypso
  assets/js/calypsoify.js
Labels: [Status] Needs Review, eCommerce Plan

#484 Add calypsoify class to body tag
  includes/class-wc-calypso-bridge-setup.php
Labels: [Status] Ready to Merge, eCommerce Plan

#479 Mark checklist complete if orders exist
  README.md
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
Labels: [Status] Needs Review, bug, eCommerce Plan

#478 Setup: Ensure MailChimp does not redirect
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-setup.php
Labels: [Status] Needs Review

#477 disable WC Admin dev docs menu item by default
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-woocommerce-admin.php
Labels: [Status] Ready to Merge, eCommerce Plan, enhancement

#483 Fix up card form styling in plugins
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#486 Override default WP navspan class styles
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#488 Update menu item colors to match Calypso
  assets/css/calypsoify.css
  assets/images/cart-active.png
  assets/images/cart-dark.png
  assets/images/cart-default.png
  assets/images/cart-hovered.png
  assets/images/cart-white.png
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#490 missed phpdoc errors on #484
  includes/class-wc-calypso-bridge-setup.php
Labels: [Status] Ready to Merge, eCommerce Plan, task

#493 Fix wc-admin onboarding layout and input issues
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, bug, eCommerce Plan
