Repository Automattic/wc-calypso-bridge, pull requests merged in 2019-01, with the labels that each got.

#427 Fix typo in method name
  class-wc-calypso-bridge.php
Labels: [Status] Ready to Merge

#425 Fix blank state button size
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#421 Forces the customizer setup checklist link to load the Starter Content.
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
  includes/class-wc-calypso-bridge-themes-setup.php
Labels: [Status] Ready to Merge, eCommerce Plan

#429 Bump version to 1.0.10
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge, eCommerce Plan

#428 Remove store guided tour files
  store-on-wpcom/class-wc-calypso-bridge.php
  store-on-wpcom/inc/class-customizer-guided-tour.php
  store-on-wpcom/tests/bootstrap.php
  store-on-wpcom/wc-calypso-bridge-class.php
  tests/bootstrap.php
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge

#430 Fix duplicated "manage your subscriptions" banner
  includes/class-wc-calypso-bridge-addons.php
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#431 Bump version to 1.0.11
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, eCommerce Plan
