Repository Automattic/wc-calypso-bridge, pull requests merged in 2019-06, with the labels that each got.

#446 Make sure obw scripts are printed in wizard
  includes/class-wc-calypso-bridge-admin-setup-wizard.php
Labels: [Status] Ready to Merge, bug, eCommerce Plan

#442 Version bump to 1.0.15
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge

#451 Update Jetpack instructions.
  README.md
Labels: [Status] Ready to Merge

#453 Ensures woo mailchimp plugin does not redirect during woo setup
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-plugins.php
Labels: [Status] Ready to Merge

#454 Update version to 1.0.16 for releasing #453
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review

#448 Update styles on the two setup screens for WooCommerce
  assets/css/calypsoify.css
Labels: [Status] Ready to Merge

#455 Updates version to 1.0.17 for releasing #448
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge
