Repository Automattic/wc-calypso-bridge, pull requests merged in 2020-06, with the labels that each got.

#545 Enable new Site Profile Wizard
  assets/css/calypsoify.css
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-setup.php
  includes/class-wc-calypso-bridge-woocommerce-admin.php
  tests/bootstrap.php
  tests/unit-tests/test-class-wc-calypso-bridge-setup.php
Labels: [Status] Needs Review

#552 Add connect logic for WooCommerce Payments.
  includes/connect/woocommerce-payments.php
Labels: [Status] Ready to Merge

#553 Prep for 1.1.7 release
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge

#556 Make host prop conditional in tracks.
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-tracks.php
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge

#563 Ignore *.swp files
  .gitignore
Labels: [Status] Ready to Merge

#561 Remove Legacy OBW
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-admin-setup-checklist.php
  includes/class-wc-calypso-bridge-setup.php
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge

#565 Ecomm: Enable Woo Core setup checklist
  includes/class-wc-calypso-bridge-woocommerce-admin.php
Labels: [Status] Ready to Merge, eCommerce Plan

#566 Prepare for 1.1.8 release
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge

#567 Remove wc-setup-checklist redirects.
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-setup.php
Labels: [Status] Needs Review

#568 Prep for 1.1.9 release
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review
