Repository Automattic/wc-calypso-bridge, pull requests merged in 2021-04, with the labels that each got.

#675 Add missing OBW Tweaks
  assets/css/ecommerce.css
Labels: [Status] Needs Review

#671 Use woocommerce_admin_onboarding_industries filter for the create page callback
  includes/class-wc-calypso-bridge-plugins.php
Labels: bug

#676 Prep for 1.7.4 release
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Ready to Merge
