Repository Automattic/wc-calypso-bridge, pull requests merged in 2021-07, with the labels that each got.

#695 Add Tooling for React Pages
  includes/class-wc-calypso-bridge-setup.php
  package-lock.json
  package.json
  src/index.js
  src/payments-welcome/index.js
Labels: [Status] In Progress, [Status] Ready to Merge

#698 Remove filters adding the Payments menu item
  includes/class-wc-calypso-bridge-setup.php
  src/index.js
Labels: [Status] Ready to Merge

#700 Install WCPay and redirect merchant KYC flow
  class-wc-calypso-bridge.php
  src/payments-welcome/index.js
Labels: [Status] Ready to Merge

#703 Conditionally load the WC Pay menu
  includes/class-wc-calypso-bridge-setup.php
Labels: [Status] Ready to Merge

#704 Add Payments Welcome Page Exit Survey
  src/payments-welcome/exit-survey-modal.tsx
  src/payments-welcome/index.tsx
  src/payments-welcome/strings.tsx
  src/payments-welcome/style.scss
  src/payments-welcome/tracks.ts
Labels: [Status] Needs Review

#705 Call activate promo REST API
  includes/class-wc-calypso-bridge-payments.php
  includes/payments/class-wc-payments-controller.php
  package-lock.json
  package.json
  src/payments-welcome/index.tsx
  wc-calypso-bridge.php
Labels: [Status] Needs Review

#709 Add new pageview track to WCPay welcome page
  src/payments-welcome/index.tsx
  src/payments-welcome/tracks.ts
Labels: [Status] Ready to Merge

#710 Add css fix for CardBody bug
  assets/css/ecommerce.css
  store-on-wpcom/assets/css/admin/store-on-wpcom.css
  store-on-wpcom/class-wc-calypso-bridge.php
Labels: bug

#712 Replace deprecated card component
  src/payments-welcome/index.tsx
  src/payments-welcome/style.scss
Labels: [Status] Ready to Merge

#714 Fix Gutenberg style conflicts
  src/payments-welcome/index.tsx
  src/payments-welcome/style.scss
Labels: [Status] Ready to Merge

#708 Re-enable WCPay menu in payments settings
  src/payments-welcome/strings.tsx
Labels: [Status] Needs Review

#718 Update promo incentive and all relevant copies
  includes/payments/class-wc-payments-controller.php
  src/payments-welcome/faq.tsx
  src/payments-welcome/strings.tsx
  src/payments-welcome/style.scss
Labels: [Status] Ready to Merge

#719 Add translated FAQs
  src/payments-welcome/faq.tsx
  src/payments-welcome/strings.tsx
Labels: [Status] Ready to Merge

#721 Merge payments branch and version bump to 1.7.9
  assets/css/wc-payments.css
  assets/fonts/WCPay.eot
  assets/fonts/WCPay.svg
  assets/fonts/WCPay.ttf
  assets/fonts/WCPay.woff
  assets/images/icon-flag.svg
  assets/images/wcpay-banner.svg
  class-wc-calypso-bridge-shared.php
  class-wc-calypso-bridge.php
  composer.json
  includes/class-wc-calypso-bridge-payments.php
  includes/class-wc-calypso-bridge-setup.php
  includes/payments/class-wc-payments-controller.php
  package-lock.json
  package.json
  readme.txt
  src/index.js
  src/payments-welcome/banner.tsx
  src/payments-welcome/cards/amex.js
  src/payments-welcome/cards/applepay.js
  src/payments-welcome/cards/cb.js
  src/payments-welcome/cards/diners.js
  src/payments-welcome/cards/discover.js
  src/payments-welcome/cards/gpay.js
  src/payments-welcome/cards/jcb.js
  src/payments-welcome/cards/maestro.js
  src/payments-welcome/cards/mastercard.js
  src/payments-welcome/cards/unionpay.js
  src/payments-welcome/cards/visa.js
  src/payments-welcome/exit-survey-modal.tsx
  src/payments-welcome/faq.tsx
  src/payments-welcome/index.js
  src/payments-welcome/index.tsx
  src/payments-welcome/strings.tsx
  src/payments-welcome/style.scss
  src/payments-welcome/tracks.ts
  store-on-wpcom/class-wc-calypso-bridge.php
  store-on-wpcom/inc/wc-calypso-bridge-nav-unification-fixes.php
  wc-calypso-bridge.php
  webpack.config.js
Labels: [Status] Ready to Merge
