Repository Automattic/wc-calypso-bridge, pull requests merged in 2021-03, with the labels that each got.

#659 Filtering wc-navigation root back url conditionally when referred by Calypso
  README.md
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-woocommerce-admin-navigation.php
  package.json
  src/index.js
  src/utils/storage.js
  src/wc-navigation-root-url.js
Labels: [Status] Ready to Merge, enhancement

#663 Setup: Prevent Creative Mail and Crowdsignal Forms redirects when activating plugins
  README.md
  includes/class-wc-calypso-bridge-setup.php
Labels: [Status] Needs Review

#662 Create WooCommerce pages if they are missing on a new installation
  includes/class-wc-calypso-bridge-plugins.php
Labels: [Status] Needs Review, bug

#664 Prep for 1.7.1 release
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review

#668 Prep for 1.7.2 release
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review
