Repository Automattic/wc-calypso-bridge, pull requests merged in 2021-02, with the labels that each got.

#634 Filter the nav back URL for ecomm plan users
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-woocommerce-admin-navigation.php
Labels: Navigation, [Status] Ready to Merge, eCommerce Plan

#638 Set survey source param for ecomm and business plans
  includes/class-wc-calypso-bridge-tracks.php
Labels: Navigation, [Status] Ready to Merge

#641 Notes: Prevent email notifications from being sent.
  includes/class-wc-calypso-bridge-filters.php
Labels: [Status] Needs Review

#650 Added help documentation filter
  includes/class-wc-calypso-bridge-filters.php
Labels: [Status] Ready to Merge

#651 Change store on wpcom order link to /wp-admin/post.php
  store-on-wpcom/class-wc-calypso-bridge.php
  store-on-wpcom/inc/wc-calypso-bridge-email-order-url.php
Labels: Store on WP.com, [Status] Needs Review

#653 Prep for 1.7.0 Release.
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review

#655 Add simple front-end tooling
  .eslintrc.js
  .gitignore
  .prettierrc.json
  README.md
  class-wc-calypso-bridge.php
  package-lock.json
  package.json
  src/index.js
  src/index.scss
  webpack.config.js
Labels: [Status] Needs Review

#654 Updating README directions to point to updated gist for setup
  README.md
Labels: [Status] Ready to Merge
