Repository Automattic/wc-calypso-bridge, pull requests merged in 2023-10, with the labels that each got.

#1318 Use the wc-admin version of the marketplace under Extensions > Discover menu item
  includes/class-wc-calypso-bridge-addons.php
  includes/class-wc-calypso-bridge-ecommerce-admin-menu.php
  readme.txt
  src/index.js
Labels: blocked

#1319 Prepare for release 2.2.17
  composer.json
  includes/class-wc-calypso-bridge-addons.php
  includes/class-wc-calypso-bridge-ecommerce-admin-menu.php
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-nl_NL.mo
  languages/wc-calypso-bridge-nl_NL.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1324 Add filter for recommended WPCOM themes
  includes/class-wc-calypso-bridge-filters.php
Labels: Woo Express

#1334 Prepare for release 2.2.18
  composer.json
  includes/class-wc-calypso-bridge-ecommerce-admin-menu.php
  includes/class-wc-calypso-bridge-filters.php
  includes/class-wc-calypso-bridge-setup.php
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1341 Prepare for release 2.2.20
  composer.json
  includes/class-wc-calypso-bridge-events.php
  includes/class-wc-calypso-bridge-hide-alerts.php
  includes/class-wc-calypso-bridge-notes.php
  includes/class-wc-calypso-bridge-plugins.php
  includes/class-wc-calypso-bridge-setup.php
  includes/notes/class-wc-calypso-bridge-choose-domain.php
  includes/notes/class-wc-calypso-bridge-free-trial-welcome.php
  includes/notes/data/class-wc-calypso-bridge-admin-note-data-store.php
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release
