Repository Automattic/wc-calypso-bridge, pull requests merged in 2023-08, with the labels that each got.

#1248 Prepare for release 2.2.6
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1254 Prepare for release 2.2.7
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1255 README update to clarify deployment process
  README.md
Labels: [Status] Needs Review

#1260 Prepare for release 2.2.8
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1273 Prepare for release 2.2.9
  composer.json
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1277 Prepare for release 2.2.10
  composer.json
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1265 Handling footer credits for Woo Express plans.
  class-wc-calypso-bridge.php
  includes/class-wc-calypso-bridge-footer-credits.php
  readme.txt
Labels: Woo Express

#1280 Prepare for release 2.2.11
  composer.json
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1289 Prepare for release 2.2.12
  composer.json
  includes/class-wc-calypso-bridge-footer-credits.php
  includes/class-wc-calypso-bridge-tracks.php
  includes/class-wc-calypso-bridge-woocommerce-admin-features.php
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release
