Repository Automattic/wc-calypso-bridge, pull requests merged in 2023-02, with the labels that each got.

#937 WooExpress: Hide the Launch task for sites on eCommerce trial
  includes/tasks/class-wc-calypso-task-launch-site.php
Labels: eCommerce Plan

#974 Remove absolute path prefix from My Home and Customer menu URLs
  includes/class-wc-calypso-bridge-ecommerce-admin-menu.php
Labels: bug, [Status] Needs Review, eCommerce Plan

#976 Release 2.0.3
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review

#987 Customize homescreen title and progress header
  readme.txt
  src/homescreen-progress-header/index.js
  src/homescreen-progress-header/progress-header.tsx
  src/homescreen-progress-header/progress-title.tsx
  src/homescreen-progress-header/style.scss
  src/homescreen-progress-header/task-list-menu.tsx
  src/index.js
Labels: [Status] Needs Review
