Repository Automattic/wc-calypso-bridge, pull requests merged in 2023-05, with the labels that each got.

#1109 Deploy Automation: Automate doing a release build.
  scripts/commands/build.js
  scripts/package.json
  scripts/release.js
  scripts/utils.js
  scripts/yarn.lock
Labels: [Status] Needs Review, [Status] In Progress, automation

#1113 README update
  README.md
Labels: [Status] Needs Review

#1115 Deploy Automation: Automate creating and pushing a release tag
  scripts/commands/build.js
  scripts/commands/tag.js
  scripts/release.js
  scripts/utils.js
Labels: [Status] Needs Review, automation

#1114 Add a workspaces section to our to-level package.json
  package-lock.json
  package.json
Labels: [Status] Needs Review

#1122 Deploy Automation: Update the changelog
  scripts/commands/build.js
  scripts/commands/readme.js
  scripts/utils.js
Labels: [Status] Needs Review, automation

#1116 Deploy Automation: Add bump version command
  package-lock.json
  package.json
  scripts/commands/bump-version.js
  scripts/package.json
  scripts/utils.js
  scripts/yarn.lock
Labels: automation

#1126 Deploy Automation: Refactoring abort code
  scripts/commands/build.js
  scripts/commands/readme.js
  scripts/commands/tag.js
  scripts/release.js
  scripts/utils.js
Labels: [Status] Needs Review, automation

#1133 Update changelog with release automation script details
  readme.txt
Labels: [Status] Needs Review

#1135 Update readme with automated deploy instructions
  README.md
Labels: [Status] Needs Review, automation

#1139 Update version 2.1.5
  composer.json
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review

#1149 Deploy Automation: Update branch name created for deploys
  scripts/commands/bump-version.js
Labels: [Status] Needs Review, automation

#1162 Add defensive code to OBW skip filter
  includes/class-wc-calypso-bridge-skip-obw.php
  readme.txt
Labels: Woo Express
