Repository Automattic/wc-calypso-bridge, pull requests merged in 2024-05, with the labels that each got.

#1470 Prepare for release 2.4.0
  composer.json
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1474 Prepare for release 2.4.1
  composer.json
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-nl_NL.mo
  languages/wc-calypso-bridge-nl_NL.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1476 Prepare for release 2.4.2
  composer.json
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-nl_NL.mo
  languages/wc-calypso-bridge-nl_NL.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1472 i18n: Load script translations
  class-wc-calypso-bridge-shared.php
  languages/wc-calypso-bridge.pot
  package-lock.json
  package.json
  scripts/commands/update-translations.js
  src/i18n-loader.js
  src/index.js
  webpack.config.js
Labels: [Status] Needs Review

#1480 i18n: Ensure i18n loader is included in the production build
  src/i18n-loader.js
  src/index.js
  webpack.config.js
Labels: type : bug, i18n
