Repository Automattic/wc-calypso-bridge, pull requests merged in 2024-01, with the labels that each got.

#1414 Prepare for release 2.3.0
  composer.json
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1418 Prepare for release 2.3.1
  composer.json
  includes/class-wc-calypso-bridge-customize-store.php
  includes/class-wc-calypso-bridge-filters.php
  includes/class-wc-calypso-bridge-hide-alerts.php
  includes/class-wc-calypso-bridge-setup-tasks.php
  includes/class-wc-calypso-bridge-woo-express-introductory-offers.php
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1421 Fix free trial banner missing border
  readme.txt
  src/introductory-offer-banner/index.js
  src/introductory-offer-banner/style.scss
Labels: [Status] Needs Review, Woo Express

#1415 Updated payment gateways info notice for free trial users
  readme.txt
  src/payment-gateway-suggestions/index.js
Labels: DO NOT MERGE

#1401 Sanitize slugs before getting page for deletion
  includes/class-wc-calypso-bridge-setup.php
  readme.txt
Labels: DO NOT MERGE

#1400 Rename "Blog" frontend navigation item to "News"
  includes/class-wc-calypso-bridge-setup.php
  readme.txt
Labels: DO NOT MERGE

#1423 Prepare for release 2.3.2
  composer.json
  includes/class-wc-calypso-bridge-ecommerce-admin-menu.php
  includes/class-wc-calypso-bridge-events.php
  includes/class-wc-calypso-bridge-jetpack.php
  includes/class-wc-calypso-bridge-notes.php
  includes/class-wc-calypso-bridge-setup.php
  includes/class-wc-calypso-bridge-woocommerce-admin-features.php
  includes/notes/class-wc-calypso-bridge-choose-domain.php
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1432 Prepare for release 2.3.3
  composer.json
  includes/class-wc-calypso-bridge-free-trial-payment-restrictions.php
  includes/class-wc-calypso-bridge-setup-tasks.php
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release

#1435 Prepare for release 2.3.4
  class-wc-calypso-bridge.php
  composer.json
  languages/wc-calypso-bridge-ar.mo
  languages/wc-calypso-bridge-ar.po
  languages/wc-calypso-bridge-de_DE.mo
  languages/wc-calypso-bridge-de_DE.po
  languages/wc-calypso-bridge-es_CL.mo
  languages/wc-calypso-bridge-es_CL.po
  languages/wc-calypso-bridge-es_ES.mo
  languages/wc-calypso-bridge-es_ES.po
  languages/wc-calypso-bridge-es_MX.mo
  languages/wc-calypso-bridge-es_MX.po
  languages/wc-calypso-bridge-fr_BE.mo
  languages/wc-calypso-bridge-fr_BE.po
  languages/wc-calypso-bridge-fr_CA.mo
  languages/wc-calypso-bridge-fr_CA.po
  languages/wc-calypso-bridge-fr_FR.mo
  languages/wc-calypso-bridge-fr_FR.po
  languages/wc-calypso-bridge-he_IL.mo
  languages/wc-calypso-bridge-he_IL.po
  languages/wc-calypso-bridge-id_ID.mo
  languages/wc-calypso-bridge-id_ID.po
  languages/wc-calypso-bridge-it_IT.mo
  languages/wc-calypso-bridge-it_IT.po
  languages/wc-calypso-bridge-ja.mo
  languages/wc-calypso-bridge-ja.po
  languages/wc-calypso-bridge-ko_KR.mo
  languages/wc-calypso-bridge-ko_KR.po
  languages/wc-calypso-bridge-pt_BR.mo
  languages/wc-calypso-bridge-pt_BR.po
  languages/wc-calypso-bridge-ru_RU.mo
  languages/wc-calypso-bridge-ru_RU.po
  languages/wc-calypso-bridge-sv_SE.mo
  languages/wc-calypso-bridge-sv_SE.po
  languages/wc-calypso-bridge-tr_TR.mo
  languages/wc-calypso-bridge-tr_TR.po
  languages/wc-calypso-bridge-zh_CN.mo
  languages/wc-calypso-bridge-zh_CN.po
  languages/wc-calypso-bridge-zh_SG.mo
  languages/wc-calypso-bridge-zh_SG.po
  languages/wc-calypso-bridge-zh_TW.mo
  languages/wc-calypso-bridge-zh_TW.po
  languages/wc-calypso-bridge.pot
  readme.txt
  wc-calypso-bridge.php
Labels: [Status] Needs Review, [Type] Release
